[package]
name = "htsengine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
htsengine-sys = { path = "../htsengine-sys" }
thiserror = "1.0"
